<?php $_order = Mage::registry('current_order'); ?>

<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('dfzgasdfgasdgon') ?></h4>

        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('sdfsdfgdfg') ?></label></td>
                        <td class="value">
                           asdasdasd
                            <?php echo $_order->getId() ?>
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>