<?php
    $order =  $this->getOrder();

    $result = $this->getNewShipHawkRate($order);

    if(($result == null) or ($result['error'])) {
        if($result['error']) {
            echo $result['error'];
        }
        return;
    }

    $is_multi_zip = $result['is_multi_zip'];
    $toOrder = $result['to_order'];
    $summ_price = $result['summ_price'];
    $rate_filter = $result['rate_filter'];
    $name_service = $result['name_service'];

    $order_id = $order->getId();
    $currensy_symbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>

<form class="my-form" name="shiphawk_form" id="shiphawk_form">
    <input type="hidden" value="<?php echo $order_id ?>" name="order_id">
    <input type="hidden" value="<?php echo $is_multi_zip ?>" name="is_multi">

<?php if ($is_multi_zip == 0) { ?>
    <ul>
        <?php foreach ($toOrder as $rate_id=>$shipments_data ) {
            $shipment_value = 'shiphawk_shipping_' . $shipments_data['name'];
            $shipment_id = 's_method_shiphawk_shipping_' . $shipments_data['name'];
            $shipping_price = $shipments_data['price'];

            ?>
            <?php if ($rate_filter == 'best') { ?>
        <li>
            <input name="shipping_method" checked type="radio" value="<?php echo $rate_id ?>" id="<?php echo $shipment_id ?>" class="radio">
            <label for="<?php echo $shipment_id ?>"><?php echo  $shipments_data['carrier'] . ' - ' . $shipments_data['name'] . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $shipping_price ?></span></label>
        </li>
                <?php }else { ?>
                <li>
                    <input name="shipping_method" type="radio" value="<?php echo $rate_id ?>" id="<?php echo $shipment_id ?>" class="radio">
                    <label for="<?php echo $shipment_id ?>"><?php echo $shipments_data['carrier'] . ' - ' . $shipments_data['name'] . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $shipping_price ?></span></label>
                </li>
            <?php } ?>
        <?php } ?>
    </ul>
    <?php }else{?>
    <ul>
            <li>
                <input type="hidden" value="<?php echo $summ_price ?>" name="multi_price">
                <input checked name="shipping_method" type="radio" value="<?php echo $name_service ?>" id="<?php echo 'multi_origin' ?>" class="radio">
                <label for="<?php echo 'multi_origin' ?>"><?php echo $name_service . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $summ_price ?></span></label>
            </li>

    </ul>
    <?php } ?>
    <input type="button" value="ShipHawk Shipment" id="submitshiphawk" />
    <span id="formLoader" style="display:none;">&nbsp;</span>
</form>

<div id="formSuccess" style="display:none;">&nbsp;</div>


<script type="text/javascript">
    //<![CDATA[

    var postUrl = '<?php echo Mage::helper("adminhtml")->getUrl("adminshiphawk/adminhtml_shipment/newbook"); ?>';

    function doAjax() {

        new Ajax.Request(postUrl, {
            method: 'post',
            parameters: $('shiphawk_form').serialize(),
            onSuccess: function(transport)  {
                responce_html  = JSON.parse(transport.responseText);
                Element.hide($('shiphawk_form'));
                $('loading-mask').hide();
                $('formSuccess').show();
                $('formSuccess').update(responce_html);
            },
            onComplete:function(request, json) {
                Element.hide($('shiphawk_form'));
                responce_html  = JSON.parse(transport.responseText);
                $('formSuccess').show();
                $('formSuccess').update(responce_html);
            }
        });

    }

    new Event.observe($('submitshiphawk'), 'click', function(e){
        e.stop();
        doAjax();
    });
    //]]>
</script>