<?php $order =  $this->getOrder();

//todo move to block!

$carrier = Mage::getModel('shiphawk_shipping/carrier');
$api = Mage::getModel('shiphawk_shipping/api');

$items = $carrier->getShiphawkItems($order);

$grouped_items_by_zip = $carrier->getGroupedItemsByZip($items);

$shippingAddress = $order->getShippingAddress();
$to_zip = $shippingAddress->getPostcode();

$ship_responces = array();
$toOrder= array();
$api_error = false;
$is_multi_zip = (count($grouped_items_by_zip) > 1) ? true : false;
$rate_filter =  Mage::helper('shiphawk_shipping')->getRateFilter();
if($is_multi_zip) {
    $rate_filter = 'best';
}

foreach($grouped_items_by_zip as $from_zip=>$items_) {

    $responceObject = $api->getShiphawkRate($from_zip, $to_zip, $items_, $rate_filter);
    $ship_responces[] = $responceObject;

    if(is_object($responceObject)) {
        $api_error = true;
        Mage::log('ShipHawk responce: '.$responceObject->error, null, 'ShipHawk.log');
    }else{
        // if $rate_filter = 'best' then it is only one rate
        if(($is_multi_zip)||($rate_filter == 'best')) {
            Mage::getSingleton('core/session')->setMultiZipCode(true);
            $toOrder[$responceObject[0]->id]['product_ids'] = $carrier->getProductIds($items_);
            $toOrder[$responceObject[0]->id]['price'] = $responceObject[0]->summary->price;
            $toOrder[$responceObject[0]->id]['name'] = $responceObject[0]->summary->service;
            $toOrder[$responceObject[0]->id]['items'] = $items_;
            $toOrder[$responceObject[0]->id]['from_zip'] = $from_zip;
            $toOrder[$responceObject[0]->id]['to_zip'] = $to_zip;
        }else{
            Mage::getSingleton('core/session')->setMultiZipCode(false);
            foreach ($responceObject as $responce) {
                $toOrder[$responce->id]['product_ids'] = $carrier->getProductIds($items_);
                $toOrder[$responce->id]['price'] = $responce->summary->price;
                $toOrder[$responce->id]['name'] = $responce->summary->service;
                $toOrder[$responce->id]['items'] = $items_;
                $toOrder[$responce->id]['from_zip'] = $from_zip;
                $toOrder[$responce->id]['to_zip'] = $to_zip;
            }
        }
    }

}
$name_service = '';
$summ_price = 0;
if(!$api_error) {
    $services = $carrier->getServices($ship_responces);


    Mage::log($services, null, 'Services.log');

    foreach ($services as $id_service=>$service) {
        if (!$is_multi_zip) {
            //add ShipHawk shipping
            //$result->append($this->_getShiphawkRateObject($service['name'], $service['price']));
        }else{
            $name_service .= $service['name'] . ', ';
            $summ_price += $service['price'];
        }
    }

    //save rate_id info for Book in PopUP
    Mage::getSingleton('core/session')->setNewShiphawkBookId($toOrder);

    Mage::log($toOrder, null, 'toOrder.log');

    //remove last comma
    if(strlen($name_service) >2) {
        if ($name_service{strlen($name_service)-2} == ',') {
            $name_service = substr($name_service,0,-2);
        }
    }

    if($is_multi_zip) {
        //add ShipHawk shipping
        //$name_service = 'Shipping from multiple locations';
        //$result->append($this->_getShiphawkRateObject($name_service, $summ_price));
    }
}

$order_id = $order->getId();
$currensy_symbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>

<form class="my-form" name="myForm2222" id="myForm2222">
    <input type="hidden" value="<?php echo $order_id ?>" name="order_id">
    <input type="hidden" value="<?php echo $is_multi_zip ?>" name="is_multi">

<?php if ($is_multi_zip == 0) { ?>
    <ul>
        <?php foreach ($toOrder as $rate_id=>$shipments_data ) {
            $shipment_value = 'shiphawk_shipping_' . $shipments_data['name'];
            $shipment_id = 's_method_shiphawk_shipping_' . $shipments_data['name'];
            $shipping_price = $shipments_data['price'];

            ?>
            <?php if ($rate_filter == 'best') { ?>
        <li>
            <input name="shipping_method" checked type="radio" value="<?php echo $rate_id ?>" id="<?php echo $shipment_id ?>" class="radio">
            <label for="<?php echo $shipment_id ?>"><?php echo $shipments_data['name'] . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $shipping_price ?></span></label>
        </li>
                <?php }else { ?>
                <li>
                    <input name="shipping_method" type="radio" value="<?php echo $rate_id ?>" id="<?php echo $shipment_id ?>" class="radio">
                    <label for="<?php echo $shipment_id ?>"><?php echo $shipments_data['name'] . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $shipping_price ?></span></label>
                </li>
            <?php } ?>
        <?php } ?>
    </ul>
    <?php }else{?>
    <ul>
            <li>
                <input type="hidden" value="<?php echo $summ_price ?>" name="multi_price">
                <input checked name="shipping_method" type="radio" value="<?php echo $name_service ?>" id="<?php echo 'multi_origin' ?>" class="radio">
                <label for="<?php echo 'multi_origin' ?>"><?php echo $name_service . ' ' ?><span class="price"><?php echo ' ' . $currensy_symbol . $summ_price ?></span></label>
            </li>

    </ul>
    <?php } ?>
    <input type="button" value="ShipHawk Shipment" id="submitshiphawk" />
    <span id="formLoader" style="display:none;">&nbsp;</span>
</form>

<div id="formSuccess" style="display:none;">&nbsp;</div>


<script type="text/javascript">
    //<![CDATA[

    var postUrl = '<?php echo Mage::helper("adminhtml")->getUrl("adminshiphawk/adminhtml_shipment/newbook"); ?>';

    function doAjax() {

        new Ajax.Request(postUrl, {
            method: 'post',
            parameters: $('myForm2222').serialize(),
            onSuccess: function(transport)  {

                responce_html  = JSON.parse(transport.responseText);
                Element.hide($('myForm2222'));

                $('loading-mask').hide();
                $('formSuccess').show();
                $('formSuccess').update(responce_html);
            },
            onLoading:function(transport)
            {

            },
            onComplete:function(request, json) {
                Element.hide($('myForm2222'));

                responce_html  = JSON.parse(transport.responseText);
                $('formSuccess').show();
                $('formSuccess').update(responce_html);
                //$('loading-mask').hide();


            }
        });

    }

    new Event.observe($('submitshiphawk'), 'click', function(e){
        e.stop();
        doAjax();
    });
    //]]>
</script>